[szurubooru]
url = "https://booru.richter-nt.de"
username = "auto-tagger"
api_token = "b55e22d9-5412-4702-9e6d-3f80ac4a5886"  # See the README.md on how to generate one
public = false  # Is your szurubooru reachable over the internet?

[auto_tagger]
saucenao_api_token = "d3b194d6885f6eed4014ba6f53d6ed01418e6eed"  # In case you want to increase your daily query limit
saucenao_enabled = true  # Set this to false and deepbooru_enabled to true if you only want to tag with DeepBooru
deepbooru_enabled = true
deepbooru_model = "./misc/deepbooru/model-resnet_custom_v3.h5"
deepbooru_threshold = "0.7"  # Define how accurate the matched tag from DeepBooru has to be
hide_progress = false  # Set this to true to hide the progress bar
# Local path where media files get downloaded temporarily if you szurubooru is not public.
# This is necessary so files can get uploaded and tagged with SauceNAO.
tmp_path = "/tmp/"

[danbooru]
user = "reluce"
api_key = "aY5ArkNfDJuV78vNq4TfXn8y"
[gelbooru]
user = "None"
api_key = "None"
[konachan]
user = "None"
password = "None"
[yandere]
user = "None"
password = "None"
[pixiv]
user = "None"
password = "None"
token = "None"

[upload_images]
source_dir = "/local/path/to/upload/dir"  # Every valid media file under this dir (recursively) will get uploaded
hide_progress = false  # Set this to true to hide the progress bar
cleanup = false  # Set this to true if images in the source directory should be deleted after upload
tags = ["tagme"]  # These tags will get set for all uploaded posts
