[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
skip-string-normalization = true


[tool.interrogate]
verbose = 2
fail-under = 95
exclude = ["tests"]
ignore-init-module = true
ignore-init-method = true


[tool.isort]
line_length = 120
lines_after_imports = 2
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "LOCALFOLDER"
known_first_party = ["szuru-toolkit"]
known_local_folder = ["src/szuru-toolkit"]
multi_line_output = 3
force_single_line = true


[tool.mypy]
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
follow_imports = "silent"
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true


[tool.poetry]
name = "szuru-toolkit"
version = "0.1.0"
description = "Python package and script collection to manage your szurubooru"
authors = ["Armin Richter <armin@fkosquad.moe>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/reluce/szurubooru-scripts"
documentation = "https://github.com/reluce/szurubooru-scripts"
keywords = ["szurubooru", "szuru", "booru"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
beautifulsoup4="^4.10.0"
Pillow="^8.4.0"
Pybooru="^4.2.2"
pygelbooru="^0.3.2"
pysaucenao="^1.6.1"
requests="^2.25.1"
tqdm="^4.59.0"
tensorflow="^2.8.0"
keras="^2.8.0"
numpy="^1.22.1"
pyszuru="^0.2.4"
tomlkit = "^0.10.0"
syncer = "^1.3.0"
loguru = "^0.6.0"
pathvalidate = "^2.5.0"
validators = "^0.18.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
interrogate = "^1.5.0"
isort = "^5.10.1"
mkdocs = "^1.2.3"
mkdocs-material = "^8.2.5"
mkdocstrings = "^0.18.1"
mypy = "^0.941"
pre-commit = "^2.17.0"
Pygments = "^2.11.2"
pytest = "^7.1.0"
pytest-cov = "^3.0.0"
